Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2026
Var
val, i, media, x, soma : real


Inicio
      i <- 1
      enquanto (i <= 10) faca
         escreva ("Digite o", i, "º valor: ")
         leia(val)
         x <- val
         soma <- soma + x
         i <- i+1
      fimenquanto

      media <- soma/10
         escreva("A media é:", media)


Fimalgoritmo