Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2026
Var
   valor:real
   desc:real
   final:real


Inicio
      escreva("Digite o valor do produto: ")
      leia(valor)

      desc <- valor / 10
      final <- valor - desc
      
      escreva("O produto de ", valor ," com o desconto fica ", final ," ,economizando ", desc )

Fimalgoritmo