Algoritmo "exercicio 33"

Var
   n1,n2,C:inteiro
   d1,d2:real


Inicio
      escreval ("Valor do Produto 1: ")
      leia (n1)
      escreval ("Valor do Produto 2: ")
      leia (n2)
      
      d1<-(n1/100)*14
      d2<-(n2/100)*17
      
      escreva ("calculando desconto")
      enquanto C<=5 faça
               Escreva (".")
               C<-C+1
      fimenquanto
      Escreval ("")
      escreval("O valor do 1º produto e seu desconto é de:R$",n1," E",d1)
      escreval("O valor do 2º produto e seu desconto é de:R$",n2," E",d2)



Fimalgoritmo