Algoritmo "exercicio 34"


Var
   A,B,so,su,mu:inteiro
   di:real

inicio
      Escreva("Digite Valor A: ")
      leia (A)
      Escreva("Digite Valor B: ")
      Leia (B)
      
      so<-A+B
      su<-A-B
      mu<-A*B
      di<-A/B
      
      Escreval("=========================================")
      
      Escreval("A soma é:",so)
      Escreval("")
      Escreval("A subtração é:",su)
      Escreval("")
      Escreval("A multiplicação é:",mu)
      Escreval("")
      Escreval("A divisão é:",di)
      
      Escreval("=========================================")
      
      
      
      

Fimalgoritmo